import puppeteer from 'puppeteer-core';
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-unsafe-swiftshader','--use-gl=angle','--no-sandbox'],defaultViewport:{width:1280,height:860}});
const p=await b.newPage(); const errs=[];
p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,140));});
p.on('pageerror',e=>errs.push('PAGEERROR '+String(e).slice(0,140)));
await p.goto('http://localhost:5173/?flat=1&reinterp=1',{waitUntil:'networkidle2',timeout:60000});
await new Promise(r=>setTimeout(r,6000));
const n=await p.evaluate(()=>document.querySelectorAll('canvas').length);
console.log('canvases:',n,'console errors:',errs.length);
for(const e of errs) console.log('  ',e);
await b.close();
