#!/usr/bin/env node
/**
 * Bakes docs/reinterp/ATTRIBUTIONS.md's table into data/strings/
 * attributions.json for the R28-4 game menu's "Credits & attributions" view
 * (src/desktop/gameMenu.ts). The md stays the source of truth (D6,
 * docs/reinterp/06_SERGIO_CHECKLIST.md) — edit IT, then re-run this:
 *   node tools/gen_attributions.mjs   (or: npm run gen-attributions)
 * Mirrors tools/gen_rooms.mjs's convention: a checked-in generated artifact,
 * regenerated by hand, not wired into `npm run build`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const MD_PATH = join(ROOT, 'docs/reinterp/ATTRIBUTIONS.md');
const OUT_PATH = join(ROOT, 'data/strings/attributions.json');
const PKG_PATH = join(ROOT, 'package.json');

const pkg = JSON.parse(readFileSync(PKG_PATH, 'utf8'));
const md = readFileSync(MD_PATH, 'utf8');

const rows = md
  .split('\n')
  .map((l) => l.trim())
  .filter((l) => l.startsWith('|') && l.endsWith('|'))
  .map((l) => l.slice(1, -1).split('|').map((c) => c.trim()));

if (rows.length < 2) {
  throw new Error('ATTRIBUTIONS.md: no markdown table found (expected a header + divider row)');
}

const [, divider, ...body] = rows;
if (!divider.every((c) => /^:?-+:?$/.test(c))) {
  throw new Error('ATTRIBUTIONS.md: second table row is not a header divider — table shape changed?');
}

const KEYS = ['asset', 'creator', 'license', 'usedAs', 'firstUsed'];
const entries = body.map((cols) => {
  const e = {};
  KEYS.forEach((k, i) => {
    e[k] = cols[i] ?? '';
  });
  return e;
});

/**
 * ⚑ S79 — CULTURAL INFLUENCE, which the table cannot hold. A licence row has a
 * creator, a licence and a file; an influence has a lineage and no licence at
 * all, and squeezing one into the other would produce exactly the abstract
 * "thanks to ballroom culture" the provenance pass names as the extraction
 * pattern. So the md carries a blockquote per influence under its own heading,
 * and each becomes one paragraph here. Blockquote lines are joined into one
 * string; a blank `>` line starts a new influence.
 */
const influences = [];
{
  let cur = [];
  for (const raw of md.split('\n')) {
    const l = raw.trim();
    if (l.startsWith('>')) {
      const body = l.slice(1).trim();
      // the credits view is plain DOM text (the frame never decorates), so
      // markdown emphasis is stripped rather than rendered
      if (body) cur.push(body.replace(/\*+/g, ''));
      else if (cur.length) { influences.push(cur.join(' ')); cur = []; }
      continue;
    }
    if (cur.length) { influences.push(cur.join(' ')); cur = []; }
  }
  if (cur.length) influences.push(cur.join(' '));
}

const out = {
  _doc:
    'GENERATED by tools/gen_attributions.mjs from docs/reinterp/ATTRIBUTIONS.md — do not hand-edit; ' +
    'edit the md and re-run the script. See D6, docs/reinterp/06_SERGIO_CHECKLIST.md.',
  projectLine: pkg.description,
  entries,
  influences
};

writeFileSync(OUT_PATH, JSON.stringify(out, null, 2) + '\n');
console.log(`wrote ${OUT_PATH} (${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}, ` +
  `${influences.length} influence${influences.length === 1 ? '' : 's'})`);
