/**
 * PRAYER-WORDS — the prayer's words, timed from Whisper, for the Un-Walk
 * wizard's "pray" step (R3-21/22, 2026-09-20).
 *
 * Same law as tools/sync-lyrics.mjs: TIMINGS come from Whisper, TEXT stays
 * authored (Whisper hears "Hold my hands" for "Fold my hands"). The authored
 * lyric is the sheet Sérgio delivered with the track; each of its words is
 * aligned to the transcript's word stream by longest-common-subsequence, and
 * any authored word Whisper did not hear is placed between its neighbours.
 * Output: data/dialog/s1_prayer.json — lines of {w, s, e} in seconds from the
 * start of the recording (fold_my_hands_tape97.mp3; the tape's prayer segment
 * begins at s1_tapes.json's `a-prayer-01.at`, which kit.ts adds).
 *
 *   node tools/prayer-words.mjs "<whisper.json>" [--write]
 */
import fs from 'node:fs';

const [whisperPath] = process.argv.slice(2);
const write = process.argv.includes('--write');
if (!whisperPath) { console.error('usage: prayer-words <whisper.json> [--write]'); process.exit(1); }

/** the authored sheet ("Fold My Hands", Sérgio, 11 July 2026), as sung: the
 *  final chorus repeats "tonight" — the transcript hears it and so does the ear */
const LINES = [
  'Fold my hands the way you showed me,',
  'keep my eyes upon the floor;',
  'all the songs I used to sing —',
  "I don't sing them anymore.",
  'Make me new, make me right,',
  'take the wrong of me tonight.',
  "I'll be still, I'll be clean,",
  "I'll be anyone but me.",
  'Wash the part of me that wanders',
  "till it's white as any wool;",
  'if I empty out my pockets',
  "you can fill me till I'm full.",
  'Shepherd, count me with the others,',
  'let me match, let me belong —',
  "if I'm quiet, if I'm careful,",
  "no one has to know I'm wrong.",
  'Make me new, make me right,',
  'take the wrong of me tonight.',
  "Tonight I'll be still, I'll be clean,",
  "I'll be anyone but me.",
  'Make me new, make me right,',
  'take the wrong of me tonight.',
  "I'll be still, I'll be clean…",
  "I'll be anyone but me."
];

const norm = (s) => s.toLowerCase().replace(/[’]/g, "'").replace(/[^a-z0-9' ]/g, ' ').split(/\s+/).filter(Boolean);
const heard = JSON.parse(fs.readFileSync(whisperPath, 'utf8')).segments
  .flatMap((seg) => seg.words ?? [])
  .map((w) => ({ w: norm(w.word)[0] ?? '', s: w.start, e: w.end })).filter((x) => x.w);
// the one transcription artifact worth naming: it never hears the F
const same = (a, b) => a === b || (a === 'fold' && b === 'hold');

const authored = [];
LINES.forEach((line, li) => line.split(/\s+/).forEach((tok) => {
  const key = norm(tok)[0];
  if (key) authored.push({ tok, key, line: li });
}));

// LCS over authored × heard
const n = authored.length, m = heard.length;
const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
for (let i = n - 1; i >= 0; i--) for (let j = m - 1; j >= 0; j--) {
  dp[i][j] = same(authored[i].key, heard[j].w) ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]);
}
let i = 0, j = 0;
while (i < n && j < m) {
  if (same(authored[i].key, heard[j].w)) { authored[i].s = heard[j].s; authored[i].e = heard[j].e; i++; j++; }
  else if (dp[i + 1][j] >= dp[i][j + 1]) i++; else j++;
}
// unmatched words sit between their timed neighbours
for (let k = 0; k < n; k++) {
  if (authored[k].s !== undefined) continue;
  let a = k - 1; while (a >= 0 && authored[a].s === undefined) a--;
  let b = k + 1; while (b < n && authored[b].s === undefined) b++;
  const t0 = a >= 0 ? authored[a].e : 0, t1 = b < n ? authored[b].s : t0 + 0.4;
  const span = (t1 - t0) / (b - a);
  authored[k].s = +(t0 + span * (k - a - 1)).toFixed(2);
  authored[k].e = +(t0 + span * (k - a)).toFixed(2);
}
const matched = authored.filter((w) => heard.some((h) => h.s === w.s)).length;

const lines = LINES.map((_, li) => authored.filter((w) => w.line === li)
  .map((w) => ({ w: w.tok, s: +w.s.toFixed(2), e: +w.e.toFixed(2) })));
const out = {
  _doc: 'THE PRAYER, WORD-TIMED (R3-21/22, 2026-09-20). Text: Sérgio\'s authored sheet ("Fold My Hands"); timings: his Whisper transcript, seconds from the start of fold_my_hands_tape97.mp3 — generated by tools/prayer-words.mjs, never hand-edited. The Un-Walk wizard\'s pray step (src/desktop/apps/kit.ts) highlights each word as it is sung; the tape\'s prayer segment starts at s1_tapes.json a-prayer-01.at, which the kit adds.',
  audio: 'fold_my_hands_tape97.mp3',
  durationSec: 139.12,
  lines
};
console.log(`${n} words authored, ${heard.length} heard, ${matched} aligned; last word ends ${authored[n - 1].e}s`);
for (const l of lines) console.log(`  ${l[0].s.toFixed(1).padStart(6)}  ${l.map((w) => w.w).join(' ')}`);
if (write) { fs.writeFileSync('data/dialog/s1_prayer.json', JSON.stringify(out, null, 2) + '\n'); console.log('wrote data/dialog/s1_prayer.json'); }
