/**
 * VOICE PASS — every line the player can read, in play order, in one document.
 *
 * ⚑ WHY THIS EXISTS. 14 dialog files carry PLACEHOLDER-draft text: my drafts,
 * awaiting Sérgio's voice. He is not a coder, and asking him to write a
 * narrative work by opening fourteen JSON files and hunting for display strings
 * among `_doc` scaffolding is how a voice pass never happens. The technical
 * faults have been getting fixed every session; the WRITING has not moved, and
 * a narrative work is its writing. This turns "edit the repo" into "read a
 * document and rewrite the lines."
 *
 * It emits `docs/VOICE_PASS.md`: play order, register marked, and — the part
 * that matters — LOCKED lines flagged so his own verbatim wording is never
 * silently overwritten by a later pass.
 *
 * Read-only. It never writes to data/.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const D = path.join(ROOT, 'data/dialog');

/** Play order, not alphabetical — the point is to read it as a player meets it. */
const ORDER = [
  ['s1_guide.json',      'ERA 1 · 1997', 'the impersonal system side-messages'],
  ['s1_kit.json',        'ERA 1 · 1997', 'the shareware kit'],
  ['s1_tapes.json',      'ERA 1 · 1997', 'the cassettes — prayer, jingle, the mixtape'],
  ['s1_irc.json',        'ERA 1 · 1997', 'the chat room, and Rob'],
  ['s1_end.json',        'ERA 1 · 1997', "⚑ the era's climax: the escalation, the packet, the diary"],
  ['s2_lamby.json',      'ERA 2 · 2003', 'the assistant arrives'],
  ['s2_media.json',      'ERA 2 · 2003', 'the infomercial'],
  ['s2_caleb.json',      'ERA 2 · 2003', '⚑ the Caleb thread — the most emotionally central scene'],
  ['s3_queue.json',      'ERA 3 · 2016', 'the correction list'],
  ['s3_comments.json',   'ERA 3 · 2016', 'the live thread'],
  ['s3_floppysheep.json','ERA 3 · 2016', 'the game on the workstation'],
  ['s4_update.json',     'ERA 4 · now',  'the last update'],
  ['s4_space.json',      'ERA 4 · now',  'the room, and the headset'],
  ['s4_l.json',          'ERA 4 · now',  '⚑ L — includes the deadname beat (READER-GATED: do not ship unreviewed)'],
  ['s4_offers.json',     'ERA 4 · now',  'the offers, the pause, the finale'],
  ['s4_ball.json',       'ERA 4 · now',  '⚑ TRANSCENDANCE — the respite. The MC.'],
];

const SKIP_KEYS = /^(_|id$|goto$|ledgerTag$|register$|era$|status$|confidence$|sources$|url|file|track|readAloudTrack|model|key)/;
const isDisplay = (k, v) =>
  typeof v === 'string' && v.length > 2 && !SKIP_KEYS.test(k) &&
  !/^(https?:|#[0-9a-f]{3,8}$|[a-z0-9_-]+\.(json|glb|mp3|png)$)/i.test(v) &&
  /[a-zA-Z]/.test(v) && /[ .,!?'"—…]/.test(v);

function walk(node, trail, out, ctx) {
  if (Array.isArray(node)) {
    node.forEach((v, i) => walk(v, [...trail, i], out, ctx));
    return;
  }
  if (node && typeof node === 'object') {
    // ⚑ THE LOCK CONVENTION, and getting it wrong is the one unforgivable bug
    // in this tool. Sérgio's own verbatim wording is marked by a SIBLING key:
    // `residue` carries both `line` and `_s_line`. (An object-wide `_s: true`
    // is also honoured.) The first version of this script skipped every key
    // beginning with `_` as scaffolding — which meant it read the lock markers
    // as noise and reported 0 locked lines across a file whose own header names
    // three of them. A worktop that presents his sentences as my drafts invites
    // exactly the overwrite this whole file exists to prevent.
    const selfLocked = node._s === true || ctx.locked;
    const lockedKeys = new Set(
      Object.keys(node).filter((k) => k.startsWith('_s_')).map((k) => k.slice(3))
    );
    const register = node.register || ctx.register;
    for (const [k, v] of Object.entries(node)) {
      if (k === '_s' || k.startsWith('_s_')) continue;
      walk(v, [...trail, k], out, { locked: selfLocked || lockedKeys.has(k), register });
    }
    return;
  }
  const key = trail[trail.length - 1];
  if (isDisplay(String(key), node)) {
    out.push({ path: trail.join('.'), text: node, locked: ctx.locked, register: ctx.register });
  }
}

let md = `STATUS: live

# THE VOICE PASS — every line a player can read, in play order

*Generated by \`node tools/voice-pass.mjs\`. **Read-only: this file is a worktop, not the source.**
The lines live in \`data/dialog/\`; each entry below carries its exact path so an edit here can be
applied back precisely.*

## How to use this
**Rewrite in place, under the line.** Leave anything you're happy with alone — silence means keep.

| mark | meaning |
|---|---|
| 🔒 | **your own verbatim wording** (\`_s\` in the data). Never rewritten by anyone, including me |
| ✎ | my draft, awaiting you |
| \`felt\` | the person. Bare — no assistant, no satire, no mechanics |
| \`operable\` | a system surface. May charm, and must collapse |
| \`respite\` | genuine queer joy. Never a trap, never revealed as fake |

⚑ **The two that carry the most weight are marked in the contents** — Era 1's ending and the Caleb
thread. If you only do two files, do those: they are the piece's emotional spine, and everything
around them is apparatus.

---

`;

let grand = 0, lockedN = 0;
const counts = [];
for (const [file, era, note] of ORDER) {
  const p = path.join(D, file);
  if (!fs.existsSync(p)) continue;
  const json = JSON.parse(fs.readFileSync(p, 'utf8'));
  const out = [];
  walk(json, [], out, { locked: false, register: null });
  if (!out.length) continue;
  grand += out.length;
  const lk = out.filter((o) => o.locked).length;
  lockedN += lk;
  counts.push([file, out.length, lk, era, note]);

  md += `## ${era} — \`${file}\`\n*${note}* · **${out.length} lines**${lk ? ` · ${lk} locked` : ''}\n\n`;
  for (const o of out) {
    const mark = o.locked ? '🔒' : '✎';
    const reg = o.register ? ` \`${o.register}\`` : '';
    md += `${mark}${reg} \`${o.path}\`\n> ${o.text.replace(/\n/g, '\n> ')}\n\n`;
  }
  md += `---\n\n`;
}

md = md.replace('---\n\n## ' + (counts[0] ? counts[0][3] : ''), () => {
  let toc = '## The whole job, in order\n\n| file | lines | |\n|---|---|---|\n';
  for (const [f, n, lk, era, note] of counts) {
    toc += `| \`${f}\` | ${n}${lk ? ` (${lk} 🔒)` : ''} | ${era} — ${note} |\n`;
  }
  toc += `| **total** | **${grand}** | ${lockedN} already yours |\n\n---\n\n## ` + counts[0][3];
  return toc;
});

fs.writeFileSync(path.join(ROOT, 'docs/VOICE_PASS.md'), md);
console.log(`voice pass: ${grand} readable lines across ${counts.length} files → docs/VOICE_PASS.md`);
console.log(`  ${lockedN} already carry your own verbatim wording (🔒, never rewritten)`);
